version: "3"
services:
  db:
    image: postgres:9.5
    logging:
      driver: "none"
  web:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      depends_on:
        - db
        - presto
      environment:
        - DATABASE_URL=postgres://postgres@db/postgres
        - PRESTO_URL=presto://presto:8080/hive/default
        - DEBUG=True
        - ALLOWED_HOSTS=localhost,127.0.0.1,
        - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      command:
        ./bin/run-dev.sh
  hive-db:
    image: postgres:9.5
    logging:
      driver: "none"
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=hive
        - POSTGRESS_PASSWORD=password
        - POSTGRES_DB=metastore

  hdfs-namenode:
    image: uhopper/hadoop-namenode:2.7.2
    logging:
      driver: "none"
    hostname: hdfs-namenode
    ports:
      - "8020:8020"
      - "50070:50070"
    environment:
      - CLUSTER_NAME=hadoop
  hdfs-datanode:
    image: uhopper/hadoop-datanode:2.7.2
    logging:
      driver: "none"
    ports:
      - "50010:50010"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
  metastore:
    image: mozdata/docker-hive-metastore:1.2.1
    logging:
      driver: "none"
    ports:
      - "9083:9083"
    depends_on:
      - hive-db
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - DB_URI=hive-db
      - DB_USER=hive
      - DB_PASSWORD=password
  presto:
    image: mozdata/docker-presto:0.151
    logging:
      driver: "none"
    depends_on:
      - metastore
      - hdfs-namenode
    ports:
      - "8080:8080"
    environment:
      - CONFIG_CONF_QUERY_MAX___MEMORY=256MB
      - CONFIG_CONF_QUERY_MAX___MEMORY___PER___NODE=256MB
      - JVM_CONF_XMX=512M
      - HIVE_CONF_HIVE_METASTORE_URI=thrift://metastore:9083
